# Generated by Django 3.0.13 on 2021-03-25 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('genre_decription', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_titel', models.CharField(max_length=100)),
                ('movie_description', models.TextField(max_length=1000)),
                ('release_date', models.DateField(verbose_name='Release date')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Genre')),
            ],
        ),
    ]
