# Generated by Django 3.0.13 on 2021-04-03 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('twitter', models.TextField(blank=True)),
                ('instagram', models.TextField(blank=True)),
                ('vimeo', models.TextField(blank=True)),
                ('behance', models.TextField(blank=True)),
                ('github', models.TextField(blank=True)),
                ('creative_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
