# Generated by Django 3.0.13 on 2021-04-03 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theStash', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='creative_username',
            new_name='user',
        ),
    ]
