# Generated by Django 3.0.13 on 2021-04-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theStash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
