# Generated by Django 3.0.13 on 2021-04-03 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theStash', '0002_auto_20210403_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('c_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('public', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theStash.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theStash.Category')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theStash.Idea')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='idea',
            field=models.ManyToManyField(through='theStash.Interest', to='theStash.Idea'),
        ),
    ]
