# Generated by Django 3.0.13 on 2021-05-05 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theStash', '0002_auto_20210505_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_interests',
        ),
    ]
