# Generated by Django 3.0.13 on 2021-04-03 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theStash', '0003_auto_20210403_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='theStash.Profile'),
        ),
    ]
