# Generated by Django 3.0.13 on 2021-04-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theStash', '0003_auto_20210420_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='.media/ideas/'),
        ),
    ]
