# Generated by Django 3.0.13 on 2021-05-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theStash', '0004_auto_20210522_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='./profilepics/'),
        ),
    ]
