# Generated by Django 3.0.13 on 2021-04-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theStash', '0004_auto_20210420_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='./media/'),
        ),
    ]
