# Generated by Django 3.0.13 on 2021-04-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theStash', '0005_auto_20210421_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='idea_category',
            field=models.ManyToManyField(related_name='idea_categories', to='theStash.Category'),
        ),
    ]
