# Generated by Django 3.0.13 on 2021-05-24 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theStash', '0005_auto_20210522_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='link1',
            new_name='behance',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='link2',
            new_name='instagram',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='link3',
            new_name='vimeo',
        ),
    ]
