# Generated by Django 3.0.13 on 2021-05-26 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theStash', '0007_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_likes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_idea', to='theStash.Idea'),
        ),
    ]
